### ISSUE TITLE
Integrate Prettier as a Pre-commit hook

### ISSUE THREAD

**Issue by areai51** [areai51/fusion#14]
Follow the steps mentioned here https://medium.com/@dovydas_s/how-much-interest-would-there-be-in-an-article-comparing-the-latest-of-angular-4-and-react-redux-accfdbea303 to setup prettier as a pre-commit

**Comment by sbmadhav** [comment]
@areai51  - The link above does not point to prettier. Was it this - https://medium.com/@brindelle/format-your-javascript-with-prettier-before-committing-177079ec356a
If yes, this would work only in OSX and Linux. Will fail in Windows.

**Comment by areai51** [comment]
haha yes that that's the right link thanks

**Comment by vinaymavi** [comment]
Prettier implemented as pre-commit githook https://github.com/pagesource/fusion-components/pull/66

**Comment by vinaymavi** [comment]
@areai51 @sbmadhav can we close this issue as #66  is merged?

**Comment by sbmadhav** [comment]
@vinaymavi  - I don't see the prettier configurations in development branch, can you check please?

**Comment by vinaymavi** [comment]
yes you are right @sbmadhav right now we do not have changes in master, changes got replaced by #75 PR -  https://github.com/pagesource/fusion-components/pull/75/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2.

can you please suggest how we can pull back these changes?

**Comment by vinaymavi** [comment]
@sbmadhav can we close now as configuration available in development branch?

**Comment by sbmadhav** [comment]
not until it is moved to master. We need to close out the eslint issue and then I'll merge to master.

**Comment by vinaymavi** [comment]
created a PR for eslint issue - https://github.com/pagesource/fusion-components/pull/76, please check provide your comments.

**Comment by sbmadhav** [comment]
Thanks Vinay
