### ISSUE TITLE
Support for sub-menu on navigation component

### ISSUE THREAD

**Issue by areai51** [areai51/fusion#15]
Allow the navigation component to render a nested set of submenu links as a dropdown

**Comment by ghost** [comment]
I have submitted a Pr for resolving this issue.Please review.
https://github.com/pagesource/fusion/pull/47

**Comment by ghost** [comment]
I have refactored the code according to the comment.Please review 
https://github.com/pagesource/fusion/pull/47

**Comment by sbmadhav** [comment]
@lazy-sunshine - Can you please add a demo for the sub menu functionality?

**Comment by sbmadhav** [comment]
@lazy-sunshine - Can you please add a demo for the sub menu functionality?

**Comment by ghost** [comment]
Please find the attached snapshot of the submenu in the navigation component

![one](https://user-images.githubusercontent.com/11867513/31886430-e53bd3c6-b811-11e7-81da-5a7c765123bf.png)
![three](https://user-images.githubusercontent.com/11867513/31886432-e588575a-b811-11e7-91a6-30400cf11700.png)
![two](https://user-images.githubusercontent.com/11867513/31886433-e5d353a4-b811-11e7-949a-b574b8f50b6f.png)
![accesible](https://user-images.githubusercontent.com/11867513/31886441-ed55493e-b811-11e7-9020-2c4d4d204868.png)

**Comment by sbmadhav** [comment]
Thanks @lazy-sunshine. Looks like the Travis CI is not propagating the changes from master then. @vinaymavi Can you please take a look? Please check Gitter.
Thanks for the PR as well @lazy-sunshine!
Our Gitter link is https://gitter.im/pagesource-fusion/Lobby
