### ISSUE TITLE
npm start command not working 

### ISSUE THREAD

**Issue by vinaymavi** [areai51/fusion#18]
npm command not working for me, getting following error. 
**Error**
![image](https://user-images.githubusercontent.com/1610828/29979065-9539e9fe-8f61-11e7-91d9-a88f8ca91412.png)

**Debug logs**

![image](https://user-images.githubusercontent.com/1610828/29979058-8bbebe18-8f61-11e7-8610-dd4797de2779.png)

**Comment by sbmadhav** [comment]
The pull request #20 should fix this issue. In the interim please run `npm run build` before you do `npm start`

**Comment by page-source** [comment]
When I run 'npm run start' ->  It doesn't hot-reload, doesn't show warnings in console.
When I run 'npm run dev'-> It hot-reloads, shows errors/warnings in console.
