### ISSUE TITLE
Advocating Yarn or NPM

### ISSUE THREAD

**Issue by sbmadhav** [areai51/fusion#21]
I see that the project is using Yarn. (Yarn.lock file and a `yarn lint` is present as pre-commit script in package json.) But in the documentation, `npm install` and `npm start` are mentioned. So for this project are you advocating the use Yarn or Node Package Modules?

**Comment by vish288** [comment]
To reach their own I guess. But we should add the line that if you use one, use it consistently. Would that work?

**Comment by sbmadhav** [comment]
I agree with you. We need to have your statement reflect in the code base. I would want to see the documentation being consistent with the code. Either we change the Readme.md file to use yarn syntax or use only NPM syntax in package json. For now, let's change to the npm syntax in package.json.

**Comment by vish288** [comment]
This has been addressed as a part of PR #30
