### ISSUE TITLE
Rename Chart components

### ISSUE THREAD

**Issue by sbmadhav** [areai51/fusion#24]
Currently, it is difficult to make changes to or search for all chart components. I suggest that we rename all the components to the following example style for easy identification/classification.
`ChartHorizontalBar`
`ChartDonut`
`ChartPie`
or
`Chart-HorizontalBar`
`Chart-Donut`
`Chart-Pie` 
or 
nest them under a subfolder `Charts`
Also, as a side note - it is easier to search for `Donut` than `Doughnut`

**Comment by vish288** [comment]
How American of you. :P

**Comment by areai51** [comment]
I propose grouping components into folders have a look at #26

**Comment by sbmadhav** [comment]
Closing in favor of issue #26
