### ISSUE TITLE
Deploy Application to a server

### ISSUE THREAD

**Issue by vinaymavi** [areai51/fusion#29]
As we have running next.js application, can we deploy it on server ?  I hope it will help to repository visitors.

**Comment by vinaymavi** [comment]
manual deployment done - https://sape-fusion.herokuapp.com/  need to integrate with #13 travis.

**Comment by sbmadhav** [comment]
The Travis integration complete this as well.
We should deploy from `master` and use `develop` branch for all ongoing development (following gitflow workflow pattern).
@areai51, @vichu1988 - your thoughts?

**Comment by vish288** [comment]
Anytime a merge happens to master, it should be auto deployed after CI build is done.
