### ISSUE TITLE
Whats your thought on integrating storybook ? 

### ISSUE THREAD

**Issue by nirbhaymandelia** [areai51/fusion#32]
@areai51 Whats your thought on integrating storybook ? (https://storybook.js.org). Although it lacks server side rendering like next but provide a nice way to explore the various states, Also we can integrate test cases using `Specs` https://github.com/mthuret/storybook-addon-specifications. I believe they can co-exist.

**Comment by areai51** [comment]
I've had a look at story book and while it is great I'm more keen on implementing a component explorer that supports like edit.. primarily looking at things like [ecology](https://github.com/FormidableLabs/ecology) or [Styleguidist](https://github.com/styleguidist/react-styleguidist) more interested in Styleguidist, do you want to give that a shot.

**Comment by sbmadhav** [comment]
Styleguidist implemented

**Comment by areai51** [comment]
w00t for styleguidist.. now just need to make some of our components compatible with it
