### ISSUE TITLE
Can we have a list of components based on priority?

### ISSUE THREAD

**Issue by vinaymavi** [areai51/fusion#34]
As we are building random components, I think it will be good if we would have a list of components on the basis of priority.
priority could be, most used components, easy to build components etc. 
@areai51 @rakeshmenon @nawazsk @sbmadhav @vikash-bhardwaj

**Comment by areai51** [comment]
Great idea @vinaymavi and that is something I've been toying with for a while.. but not had a chance to get to it.. anybody interested in giving it a first pass?

**Comment by nawazsk** [comment]
That's great. Is there any place where we can list all the components which needs to implement? or we can create list of tickets for components, so who ever will be available can pick up the task, assign to self and start working on it.

**Comment by areai51** [comment]
my suggestion would be to create one ticket for each component, so that we can detail out the props and other details of how the component should work. We can then create labels called p1, p2 etc and assign it to the ticket based on which components we would like to take up first

**Comment by sbmadhav** [comment]
I have started creating a list of components and added some details on the features that should be there in each component. Please take a look and prioritize.
