### ISSUE TITLE
Move to Feature Branch Workflow

### ISSUE THREAD

**Issue by sbmadhav** [areai51/fusion#35]
I highly recommend all members to move to Feature Branch Workflow - https://www.atlassian.com/git/tutorials/comparing-workflows#feature-branch-workflow
All non-member can use Forking Workflow - https://www.atlassian.com/git/tutorials/comparing-workflows#forking-workflow

As a part of this process, we need to remove the following branches. Seeking your permission for the same. If these are already stale branches, let me know. If not, please merge your work to master, so that this can be deleted.

- DKV/Fusion - @dkvellin 
- SJ/Fusion - @shalinijha92 
- fusion - @dalalayan1 
- styled-components - @dkvellin 
- themefix - @shafeeqonline

**Comment by vish288** [comment]
I was going to suggest that. we need a strategy for release and versioning as well preferably.

**Comment by areai51** [comment]
The reason I kept things open was to keep the momentum going and get enough meat in before we start  putting in checks and balances. Having said that and given that we now have Travis and heroku deployments I believe its time to move to feature branch strategy.

Feel free to delete the branches except for the styled-components branch.. there is a remote thought that we might choose to make fusion available using styled-components., but happy to hear your thoughts on this.

**Comment by sbmadhav** [comment]
@areai51  - if we need the styled-components branch we should move it to feature/styled-components to keep it consistent with the branching strategy.

@vichu1988  - if we need release and versioning as well, we can use Gitflow Workflow - https://www.atlassian.com/git/tutorials/comparing-workflows#gitflow-workflow or an equivalent variant to git-flow workflow - Which will use `master` as the main development branch

**Comment by sbmadhav** [comment]
Gitflow work flow has been initiated in the repository.
Please follow the link to learn about the branching and merging strategy.
https://www.atlassian.com/git/tutorials/comparing-workflows#gitflow-workflow
