### ISSUE TITLE
Component Request - Back To Top

### ISSUE THREAD

**Issue by sbmadhav** [areai51/fusion#50]
# Back To Top Component

### The component has the following elements: 

- [ ] "BACK TO TOP" link:

1. The default name should be defaulted to "BACK TO TOP". However, should have the ability to change the link name if needed.
2. Should be able to Align left or right.

- [ ] Floating Div (mandatory):  

1. Should be able to define an icon for the div
2. There will be a fade in/out animation, when the div appears. 
3. The Div displays at the bottom-right corner of the page.

**Comment by ghost** [comment]
I want to work on this

**Comment by sbmadhav** [comment]
@lazy-sunshine - Please feel free to start working on this
