### ISSUE TITLE
Travis build is failing 

### ISSUE THREAD

**Issue by vinaymavi** [areai51/fusion#65]
Travis build is failing

**Comment by vinaymavi** [comment]
Removing eslinting for now as this is causing build failure.

**Comment by vish288** [comment]
I think that's a bad idea.. the idea is to get the files fixed , even if it means the build fails until then!

**Comment by vinaymavi** [comment]
@vichu1988  eslint all errors resolved in PR https://github.com/pagesource/fusion-components/pull/66 including githook implementation

**Comment by vinaymavi** [comment]
As PR is merged closing this issue.
